### ISSUE TITLE
Emails with key not submitted

### ISSUE THREAD

**Issue by klokan** [klokantech/www.osmnames.org#1]
The emails is not submmited yet - and the green message box does not report any status after click on "Send".

Please make input for email bigger.

http://osmnames.org/api/?msg=

**Comment by daliborjanak** [comment]
I'm working on it. Everything is ok in development but on production no and
i dont know why. Maybe cors

Dne 5. 10. 2016 11:13 napsal uživatel "Petr Pridal" <
notifications@github.com>:

Assigned #1 https://github.com/OSMNames/www.osmnames.org/issues/1 to
@daliborjanak https://github.com/daliborjanak.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/OSMNames/www.osmnames.org/issues/1#event-812963953,
or mute
the thread

**Comment by daliborjanak** [comment]
Finally, http post was redirected to https get so it removed params. One letter fix in d202c283e2fea00ee9f41ca841b8f4619ce86e19
